---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    _systemd_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in systemd_exporter_web_listen_address"

- name: Assert that systemd version is >= 235 when enabling ip accounting or measuring restart count
  assert:
    that:
      - _systemd_exporter_systemd_version | int >= 232
  when: systemd_exporter_enable_ip_accounting or systemd_exporter_enable_restart_count

- name: Set user and group to root to allow access to /proc/X/fd
  set_fact:
    _systemd_exporter_system_group: "root"
    _systemd_exporter_system_user: "root"
  when: systemd_exporter_enable_file_descriptor_size

- name: Check if systemd_exporter is installed
  stat:
    path: "{{ _systemd_exporter_binary_install_dir }}/systemd_exporter"
  register: __systemd_exporter_is_installed
  check_mode: false
  tags:
    - systemd_exporter_install

- name: Gather currently installed systemd_exporter version (if any)
  command: "{{ _systemd_exporter_binary_install_dir }}/systemd_exporter --version"
  changed_when: false
  register: __systemd_exporter_current_version_output
  check_mode: false
  when: __systemd_exporter_is_installed.stat.exists
  tags:
    - systemd_exporter_install
    - skip_ansible_lint

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/povilasv/systemd_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set systemd_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        systemd_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - systemd_exporter_version == "latest"
    - systemd_exporter_binary_local_dir | length == 0
  delegate_to: localhost
  run_once: true

- block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/povilasv/systemd_exporter/releases/download/v' + systemd_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        systemd_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('linux-' + go_arch + '.tar.gz') in item"
  delegate_to: localhost
  when: systemd_exporter_binary_local_dir | length == 0
